import React,{useEffect,useMemo,useState,Suspense,lazy} from 'react';
import {ArrowUpRight,ArrowRight,Check,ChevronRight,Download,Settings2,Sun,Moon,Network,MapPin,BookOpen,Code2,ClipboardCheck,Layers,RotateCcw,Box,Search,ExternalLink,Globe2,Info,X} from 'lucide-react';
import {buildGraph,filterPlaces,validateConfig,validateLocalPlaces,safeUrl} from './engine.js';
import {NetworkView,SpatialView,BarSummary} from './Visuals.jsx';
import {STUDIOS,PACKAGES,SOURCES,TEAM_TEMPLATE} from './content.js';
const Scene3D=lazy(()=>import('./Scene3D.jsx'));
const EDITION=__EDITION__,BASE=import.meta.env.BASE_URL;
const defaults={courseTitle:'INFOSCI 301',semester:'Autumn 2026 · Week 4',instructor:'Prof. Luyao Zhang',defaultStudio:'network',defaultTheme:'light',enable3D:true,maxVisiblePapers:30,allowLocalData:true,githubRepo:'',githubBranch:'main',notebookPath:'public/notebooks',spaceUrl:'',vercelUrl:''};
function readSaved(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}}
function download(name,data,type='text/plain'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([data],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Link({href,children,...props}){return <a href={href} target="_blank" rel="noreferrer" {...props}>{children}<ArrowUpRight size={14}/></a>;}
function Field({label,children,hint}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
const tabs=[['explore','Explore',Layers],['guide','Four-level walkthrough',BookOpen],['code','Code & packages',Code2],['evidence','Evidence & team claim',ClipboardCheck],['sources','Sources & inspiration',Globe2]];
export default function App(){
  const [config,setConfig]=useState(defaults),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[data,setData]=useState(null);
  const [studio,setStudio]=useState('network'),[tab,setTab]=useState('explore'),[level,setLevel]=useState(0),[theme,setTheme]=useState(EDITION==='immersive'?'dark':'light'),[mode,setMode]=useState(EDITION==='immersive'?'3d':'2d');
  const [maxPapers,setMaxPapers]=useState(30),[since,setSince]=useState(2019),[search,setSearch]=useState(''),[layout,setLayout]=useState('force'),[metric,setMetric]=useState('degree'),[depth,setDepth]=useState(1),[labels,setLabels]=useState(true),[selected,setSelected]=useState(null),[resetKey,setResetKey]=useState(0);
  const [dataset,setDataset]=useState('heritage'),[from,setFrom]=useState(1965),[to,setTo]=useState(2026),[group,setGroup]=useState('All'),[projection,setProjection]=useState('mercator'),[encoding,setEncoding]=useState('points'),[localData,setLocalData]=useState(null);
  const [notes,setNotes]=useState(()=>readSaved('atlas-evidence-v2',{})),[checks,setChecks]=useState(()=>readSaved('atlas-checks-v2',{})),[team,setTeam]=useState(()=>readSaved('atlas-team-v2',TEAM_TEMPLATE)),[saved,setSaved]=useState('Saved on this device only');
  const [settings,setSettings]=useState(false),[configText,setConfigText]=useState(''),[notice,setNotice]=useState(''),[language,setLanguage]=useState('python'),[packageFilter,setPackageFilter]=useState('all');
  useEffect(()=>{Promise.all(['config.json','data/emerging-tech.json','data/heritage.json','data/earth-events.json','data/world.json','data/provenance.json'].map(u=>fetch(BASE+u).then(r=>{if(!r.ok)throw Error(u+': '+r.status);return r.json();}))).then(([c,papers,heritage,earth,world,provenance])=>{const cfg={...defaults,...validateConfig(c)};setConfig(cfg);setConfigText(JSON.stringify(cfg,null,2));setMaxPapers(cfg.maxVisiblePapers);setStudio(new URLSearchParams(location.search).get('studio')==='spatial'?'spatial':cfg.defaultStudio);setTheme(EDITION==='immersive'?'dark':cfg.defaultTheme);if(!cfg.enable3D)setMode('2d');setData({papers,heritage,earth,world,provenance});setLoaded(true);}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{document.documentElement.dataset.theme=theme;},[theme]);
  useEffect(()=>{if(!settings)return;const previous=document.activeElement,dialog=document.querySelector('[role="dialog"]');dialog?.querySelector('button,textarea')?.focus();
    const handle=e=>{if(e.key==='Escape')setSettings(false);if(e.key==='Tab'){const items=[...dialog.querySelectorAll('button:not([disabled]),textarea,input,select,a[href]')],first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};
    document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);previous?.focus();};
  },[settings]);
  useEffect(()=>{try{localStorage.setItem('atlas-evidence-v2',JSON.stringify(notes));localStorage.setItem('atlas-checks-v2',JSON.stringify(checks));localStorage.setItem('atlas-team-v2',JSON.stringify(team));setSaved('Saved on this device only');}catch{setSaved('Local storage unavailable—export your work before leaving.');}},[notes,checks,team]);
  const graph=useMemo(()=>buildGraph(data?.papers||[],maxPapers,since,studio==='network'?search:''),[data,maxPapers,since,search,studio]);
  const allPlaces=dataset==='local'?localData||[]:data?.[dataset]||[];
  const places=useMemo(()=>filterPlaces(allPlaces,{from,to,group,search:studio==='spatial'?search:''}),[allPlaces,from,to,group,search,studio]);
  const groups=[...new Set(allPlaces.map(p=>p.group))].sort(),yearMin=allPlaces.length?Math.min(...allPlaces.map(r=>r.year)):1965,yearMax=allPlaces.length?Math.max(...allPlaces.map(r=>r.year)):2026;
  const network=studio==='network',s=STUDIOS[studio],step=s.levels[level],noteKey=studio+'-'+level;
  const complete=s.levels.filter((_,i)=>checks[studio+'-'+i]).length;
  function changeStudio(st){setStudio(st);setSearch('');setSelected(null);setLevel(0);setNotice('');}
  function changeDataset(ds){setDataset(ds);setSelected(null);setGroup('All');setSearch('');const rows=ds==='local'?localData||[]:data?.[ds]||[];if(rows.length){setFrom(Math.min(...rows.map(r=>r.year)));setTo(Math.max(...rows.map(r=>r.year)));}}
  function reset(){setSearch('');setSelected(null);setMaxPapers(config.maxVisiblePapers);setSince(2019);setLayout('force');setMetric('degree');setDepth(1);setLabels(true);setFrom(yearMin);setTo(yearMax);setGroup('All');setProjection('mercator');setEncoding('points');setResetKey(k=>k+1);}
  function exportEvidence(){download('INFOSCI301_validation_record.json',JSON.stringify({exportedAt:new Date().toISOString(),course:config.courseTitle,edition:EDITION,notes,selfReportedEvidence:checks,team,settings:{studio,layout,metric,maxPapers,since,dataset,from,to,group,projection,encoding,mode},provenance:data.provenance},null,2),'application/json');}
  function noteArea(index){const key=studio+'-'+index,st=s.levels[index];return <div className="note-block" key={key}><h3>{index+1}. {st.name}</h3><p>{st.output}</p><textarea aria-label={st.name+' evidence note'} value={notes[key]||''} placeholder={st.prompt} onChange={e=>setNotes({...notes,[key]:e.target.value})} rows="5"/><label className="checkline"><input type="checkbox" checked={!!checks[key]} onChange={e=>setChecks({...checks,[key]:e.target.checked})}/> Evidence recorded (self-report, not instructor approval)</label></div>;}
  function colabLink(file){const parts=(config.notebookPath+'/'+file).split('/').map(encodeURIComponent).join('/');return config.githubRepo?`https://colab.research.google.com/github/${config.githubRepo}/blob/${encodeURIComponent(config.githubBranch)}/${parts}`:'';}
  async function importLocal(e){try{const file=e.target.files[0];if(!file)return;if(file.size>2e6)throw Error('Maximum local file size is 2 MB.');const records=validateLocalPlaces(JSON.parse(await file.text()));setLocalData(records);setDataset('local');setGroup('All');setSearch('');setSelected(null);setFrom(Math.min(...records.map(r=>r.year)));setTo(Math.max(...records.map(r=>r.year)));setNotice(`Loaded ${records.length} records in this browser only. No upload to a server.`);}catch(err){setNotice(err.message);}e.target.value='';}
  function applyConfig(){try{const c={...defaults,...validateConfig(JSON.parse(configText))};setConfig(c);setMaxPapers(c.maxVisiblePapers);setTheme(c.defaultTheme);changeStudio(c.defaultStudio);if(!c.enable3D)setMode('2d');setNotice('Configuration applied for this session. Download config.json to make it the deployed default.');setSettings(false);}catch(e){setNotice(e.message);}}
  const file=network?'INFOSCI301_Week4_Network_Studio_Colab.ipynb':'INFOSCI301_Week4_Spatiotemporal_Studio_Colab.ipynb';
  if(error)return <main className="load-error"><h1>Atlas Studio could not load its data.</h1><p>{error}</p><p>Serve the built folder over HTTP (not file://). Check the data/ and config.json files.</p><button onClick={()=>location.reload()}>Retry</button></main>;
  if(!loaded)return <main className="loading"><div className="brand-symbol"><Network/></div><h1>Opening Atlas Studio</h1><p>Loading bundled, provenance-documented teaching data…</p></main>;
  return <><a className="skip" href="#main">Skip to studio</a><header className="header"><a className="brand" href="#main"><span className="brand-symbol"><Network size={22}/></span><span>ATLAS <b>STUDIO</b><small>{config.courseTitle} · {EDITION==='immersive'?'IMMERSIVE EDITION':'GUIDED EDITION'}</small></span></a><div className="header-right"><span className="semester">{config.semester}</span><button className="icon-button" aria-label="Toggle color theme" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><button onClick={()=>{setConfigText(JSON.stringify(config,null,2));setSettings(true);}}><Settings2 size={16}/>Configure</button></div></header>
  <div className="studio-nav"><div className="studio-switch" role="group" aria-label="Choose studio"><button className={network?'active':''} onClick={()=>changeStudio('network')}><Network size={18}/> Network intelligence</button><button className={!network?'active':''} onClick={()=>changeStudio('spatial')}><MapPin size={18}/> Place & time intelligence</button></div><span className="local-badge"><i/>Real data · no API key</span></div>
  <nav className="tabs" aria-label="Studio sections">{tabs.map(([key,label,Icon])=><button key={key} aria-current={tab===key?'page':undefined} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={16}/>{label}</button>)}</nav>
  <main id="main"><section className="hero"><div><p className="eyebrow">{s.tag}</p><h1>{s.title}</h1><p className="lede">{s.subtitle}</p></div><div className="progress"><span>{String(complete).padStart(2,'0')}<small>/ 04</small></span><p>levels with evidence<br/><small>self-reported, not graded</small></p></div></section>
  {notice&&<div className="notice" role="status"><Info size={17}/>{notice}<button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={16}/></button></div>}
  <div className="level-strip" aria-label="Four validation levels">{s.levels.map((st,i)=><button key={st.name} className={i===level?'active':''} onClick={()=>{setLevel(i);if(!['guide','explore','evidence'].includes(tab))setTab('guide');}}><span>{checks[studio+'-'+i]?<Check size={15}/>:i+1}</span><div><small>LEVEL {i+1}</small>{st.name}</div><ChevronRight size={16}/></button>)}</div>
  {tab==='explore'&&<><div className="explore-grid"><section className="visual-panel"><div className="panel-top"><div><p className="eyebrow">LIVE DATA WORKBENCH</p><h2>{network?'A map of ideas—not a ranking of truth':dataset==='earth'?'Earth events in place and time':'Heritage recognition through time'}</h2></div><div className="view-switch"><button className={mode==='2d'?'active':''} onClick={()=>setMode('2d')}>2D</button>{config.enable3D&&<button className={mode==='3d'?'active':''} onClick={()=>setMode('3d')}><Box size={15}/>3D</button>}</div></div>
  <div className="chart-toolbar"><label className="search"><Search size={17}/><input aria-label="Search current dataset" placeholder={network?'Search paper or topic…':'Search place or category…'} value={search} onChange={e=>{setSearch(e.target.value);setSelected(null);}}/></label><button onClick={reset}><RotateCcw size={15}/>Reset</button></div>
  <div className="data-pills">{network?<><span><b>{graph.paperCount}</b> papers</span><span><b>{graph.nodes.length-graph.paperCount}</b> topics</span><span><b>{graph.links.length}</b> classified-under links</span></>:<><span><b>{places.length.toLocaleString()}</b> visible records</span><span>{from}—{to}</span><span>{dataset==='heritage'?'Designation IDs':dataset==='earth'?'Dated geometries':'Local records'}</span></>}</div>
  {mode==='3d'?<Suspense fallback={<div className="scene-loading">Loading the optional 3D engine…</div>}><Scene3D graph={graph} rows={places} allRows={allPlaces} network={network} onSelect={setSelected} onFallback={()=>setMode('2d')} resetKey={resetKey}/></Suspense>:network?<NetworkView key={resetKey} graph={graph} layout={layout} metric={metric} selected={selected} onSelect={setSelected} depth={depth} labels={labels}/>:<SpatialView key={resetKey} allData={allPlaces} rows={places} world={data.world} dataset={dataset} projection={projection} encoding={encoding} selected={selected} onSelect={setSelected}/>}
  <div className="boundary"><Info size={17}/><p>{network?s.boundary:dataset==='earth'?'NASA EONET dated geometries are observations, not a complete hazard inventory or a measure of people affected.':s.boundary}</p></div></section>
  <aside className="control-panel"><div className="aside-heading"><Settings2 size={17}/><h2>Make one comparison</h2></div>{network?<>
    <Field label={'Visible papers · '+maxPapers} hint="First matching records in the bundled search sample."><input aria-label="Visible papers" type="range" min="5" max="60" step="5" value={maxPapers} onChange={e=>{setMaxPapers(+e.target.value);setSelected(null);}}/></Field>
    <Field label={'Published since · '+since}><input aria-label="Publication start year" type="range" min="2019" max="2026" value={since} onChange={e=>{setSince(+e.target.value);setSelected(null);}}/></Field>
    <Field label="2D layout"><select value={layout} onChange={e=>{setLayout(e.target.value);setMode('2d');}}><option value="force">Force-directed · overview</option><option value="circular">Circular · ordering comparison</option><option value="bipartite">Bipartite · paper ↔ topic</option><option value="matrix">Adjacency matrix · density</option></select></Field>
    <Field label="2D node-size metric"><select value={metric} onChange={e=>{setMetric(e.target.value);setMode('2d');}}><option value="degree">Degree · direct connections</option><option value="pagerank">PageRank · recursive centrality</option></select></Field>
    <Field label="2D neighborhood depth"><select value={depth} onChange={e=>{setDepth(+e.target.value);setMode('2d');}}><option value="1">1 hop · direct neighbors</option><option value="2">2 hops · papers sharing a topic</option></select></Field>
    <label className="checkline"><input type="checkbox" checked={labels} onChange={e=>setLabels(e.target.checked)}/>Show frequent-topic labels in 2D</label>
  </>:<>
    <Field label="Dataset"><select value={dataset} onChange={e=>changeDataset(e.target.value)}><option value="heritage">NYC cultural heritage · core</option><option value="earth">NASA EONET · Earth extension</option>{localData&&<option value="local">Your local data · browser only</option>}</select></Field>
    <Field label={`Start year · ${from}`}><input aria-label="Start year" type="range" min={yearMin} max={yearMax} value={from} onChange={e=>{setFrom(Math.min(+e.target.value,to));setSelected(null);}}/></Field>
    <Field label={`End year · ${to}`}><input aria-label="End year" type="range" min={yearMin} max={yearMax} value={to} onChange={e=>{setTo(Math.max(+e.target.value,from));setSelected(null);}}/></Field>
    <Field label={dataset==='heritage'?'Borough':'Category'}><select value={group} onChange={e=>{setGroup(e.target.value);setSelected(null);}}><option>All</option>{groups.map(g=><option key={g}>{g}</option>)}</select></Field>
    <Field label="2D encoding"><select value={encoding} onChange={e=>{setEncoding(e.target.value);setMode('2d');}}><option value="points">Individual point marks</option><option value="grid">Screen-grid aggregation</option></select></Field>
    {dataset==='earth'&&<Field label="2D world projection"><select value={projection} onChange={e=>{setProjection(e.target.value);setMode('2d');}}><option value="mercator">Mercator · shape / polar distortion</option><option value="equalEarth">Equal Earth · equal-area context</option></select></Field>}
    {config.allowLocalData&&<details><summary>Use your own non-sensitive data</summary><p className="micro">JSON array: id, title, group, date (YYYY-MM-DD), lon, lat, optional url. ≤5,000 records / 2 MB. Stays in memory; never uploaded. Do not include personal/sensitive locations.</p><label className="file-input">Choose local JSON<input type="file" accept="application/json,.json" onChange={importLocal}/></label><button onClick={()=>download('place-data-schema.json',JSON.stringify([{id:'replace-with-record-id',title:'Replace with sourced place',group:'Category',date:'2026-09-18',lon:0,lat:0,url:''}],null,2))}>Download schema (not real data)</button></details>}
  </>}
  <div className="step-prompt"><span className="eyebrow">LEVEL {level+1} · CURRENT QUESTION</span><h3>{step.question}</h3><button className="text-button" onClick={()=>setTab('guide')}>See the guided experiment<ArrowRight size={16}/></button></div></aside></div>
  <div className="under-grid"><BarSummary rows={network?graph:places} network={network} onChoose={setSelected}/><section className="record-panel"><p className="eyebrow">INSPECT A RECORD</p>{selected?<><h3>{selected.label||selected.title}</h3><p>{network?`${selected.type} · degree ${selected.degree} · PageRank ${selected.pagerank.toFixed(4)}`:`${selected.group} · ${selected.date} · ${selected.lat.toFixed(5)}, ${selected.lon.toFixed(5)}`}</p>{selected.buildingRecords&&<p className="micro">{selected.buildingRecords} retained valid building records for this designation; first valid coordinate shown.</p>}{safeUrl(selected.url||'')&&<Link href={safeUrl(selected.url)}>Open original record</Link>}<button className="text-button" onClick={()=>setSelected(null)}>Clear selection</button></>:<><h3>Select a node, place or table row.</h3><p>Inspect the record before interpreting a pattern. Source links remain separate from model or visual inferences.</p></>}</section></div>
  <details className="record-table"><summary>Accessible record table · {network?graph.nodes.length:places.length} records · export available</summary><button onClick={()=>download('filtered-records.json',JSON.stringify(network?graph:{records:places,provenance:data.provenance},null,2),'application/json')}><Download size={15}/>Export filtered data + context</button><div className="table-scroll"><table><thead><tr><th>{network?'Node / source title':'Place / event'}</th><th>{network?'Type':'Group'}</th><th>{network?'Year / degree':'Date'}</th><th>Inspect</th></tr></thead><tbody>{(network?graph.nodes:places).slice(0,250).map(r=><tr key={r.id}><td>{r.label||r.title}</td><td>{r.type||r.group}</td><td>{network?`${r.year||'Topic'} / ${r.degree}`:r.date}</td><td><button onClick={()=>setSelected(r)} aria-label={'Inspect '+(r.label||r.title)}>Select</button></td></tr>)}</tbody></table></div><p className="micro">On-screen table capped at 250 records for readability; export contains every filtered record.</p></details></>}
  {tab==='guide'&&<section className="guide-grid"><article className="lesson"><p className="eyebrow">LEVEL {level+1} / 4 · {step.name.toUpperCase()}</p><h2>{step.verb}</h2><p className="big-question">{step.question}</p><ol className="actions">{step.actions.map(a=><li key={a}>{a}</li>)}</ol><div className="callout"><h3>What would count as validation?</h3><p>{step.validate}</p></div><div className="compare-grid"><div><h3>Keep fixed</h3><p>{network?'The source snapshot and relationship definition. When comparing layouts, use the same nodes and edges.':'The record unit, date meaning and data snapshot. Keep the year window fixed when comparing encodings.'}</p></div><div><h3>Vary · record · compare</h3><p>{network?'Vary one layout, metric or sample setting. Record the task answer, errors and interpretation. Compare with the basic count chart.':'Vary the window, encoding or projection one at a time. Record the count and user interpretation. Compare with the basic timeline and 2D map.'}</p></div></div><h3>The purposeful addition to your final project</h3><p>{step.transfer}</p><div className="button-row"><button onClick={()=>setTab('explore')}><Layers size={17}/>Try it in the workbench</button><button className="primary" onClick={()=>setLevel(Math.min(3,level+1))} disabled={level===3}>Next level<ArrowRight size={16}/></button></div><p className="micro">Return upstream when evidence fails. This is a nested validation model, not a one-way checklist.</p></article><aside className="evidence-aside">{noteArea(level)}<p className="micro">{saved}. Avoid names, contact details and sensitive field notes.</p><button onClick={exportEvidence}><Download size={16}/>Export evidence record</button></aside></section>}
  {tab==='code'&&<section><div className="code-intro"><div><p className="eyebrow">CHOOSE → INSPECT → RUN → JUSTIFY</p><h2>One core route. Optional depth.</h2><p>The original 38-idiom atlas, Python/R recipes and package-selection logic remain available. Start with the active advanced studio; expand only when your question requires it.</p></div><Link href={BASE+'notebooks/legacy-idiom-atlas.html'} className="button-link">Open original idiom atlas</Link></div><div className="notebook-grid">{['network','spatial'].map(kind=>{const name=kind==='network'?'Network':'Spatiotemporal',fname=`INFOSCI301_Week4_${name}_Studio_Colab.ipynb`,preview=`INFOSCI301_Week4_${name}_Studio_Executed.html`;return <article key={kind} className="notebook-card"><span className="eyebrow">{kind==='network'?'STUDIO 01':'STUDIO 02'}</span><h3>{name} Python / Colab</h3><p>{kind==='network'?'Layouts, centrality, communities and knowledge-graph foundations.':'Maps, timelines, projections, Earth observations and heritage records.'}</p><div className="button-row"><a className="button-link primary" href={BASE+'notebooks/'+fname} download><Download size={15}/>Notebook</a><Link href={BASE+'notebooks/'+preview}>Read executed output</Link></div>{colabLink(fname)?<Link href={colabLink(fname)}>Open in Google Colab</Link>:<p className="micro">To run: download → Colab → File → Upload notebook. Configure githubRepo for a direct Colab button.</p>}</article>;})}</div>
  <section className="recipe"><div className="panel-top"><div><p className="eyebrow">ACTIVE STATE → REPRODUCIBLE RECIPE</p><h3>{network?'Build the same paper–topic abstraction':'Build the same heritage abstraction'}</h3></div><div className="view-switch">{['python','r','browser'].map(lang=><button key={lang} className={language===lang?'active':''} onClick={()=>setLanguage(lang)}>{lang==='r'?'R':lang}</button>)}</div></div><p>{language==='browser'?'These implementation parameters describe the live app. See src/engine.js, Visuals.jsx and Scene3D.jsx in the source package.':language==='r'?'Equivalent R recipe for your adaptation; R was not executed in this release. Use the Python notebook for the executed learning route.':'Python adaptation using the bundled data snapshot. Notebook execution is separate from the browser runtime.'}</p><pre><code>{recipe(network,language,{maxPapers,since,layout,metric,depth,from,to,group,dataset})}</code></pre><button onClick={()=>download(network?'network-recipe.'+(language==='r'?'R':'txt'):'spatial-recipe.'+(language==='r'?'R':'txt'),recipe(network,language,{maxPapers,since,layout,metric,depth,from,to,group,dataset}))}><Download size={15}/>Download current recipe</button></section>
  <section className="packages"><div className="section-heading"><h2>Algorithm & package gallery</h2><select aria-label="Filter packages" value={packageFilter} onChange={e=>setPackageFilter(e.target.value)}><option value="all">Both studios</option><option value="network">Network</option><option value="spatial">Spatial–temporal</option></select></div><p>Execution status is explicit. A saved preview is not proof that every optional package will run in your environment.</p><div className="package-grid">{PACKAGES.filter(p=>packageFilter==='all'||p[5]===packageFilter).map(([name,task,status,url,output])=><article key={name}><h3>{name}</h3><p>{task}</p><span className="status-label">{status}</span><div className="button-row"><Link href={url}>Documentation</Link>{output&&<Link href={BASE+'notebooks/outputs/'+output}>Saved artifact</Link>}</div></article>)}</div></section>
  <div className="callout"><h3>NLP knowledge graphs: do not skip the evidence layer</h3><p>Entity mentions → normalized entities → proposed relation → supporting source span → human verification → graph. Store source URL, extraction method, confidence and verified/inferred status on every edge. Co-occurrence and topic assignment are useful exploratory structures, but neither is a factual relation. Evaluate sampled extractions against human annotations before making communication claims.</p></div></section>}
  {tab==='evidence'&&<section><div className="section-heading"><div><p className="eyebrow">YOUR HUMAN JUDGMENT IS THE OUTPUT</p><h2>From exploration to a defensible project</h2></div><button className="primary" onClick={exportEvidence}><Download size={16}/>Export all evidence</button></div><p>{saved}. Nothing here is sent to an instructor or server. Export and submit through your course platform.</p><div className="evidence-grid">{s.levels.map((_,i)=>noteArea(i))}</div><section className="team-section"><h2>Post before leaving class · claim your team</h2><p>One post per team. Build a shared question from individual contributions. All three idiom types must serve a task; do not add a network or map solely to satisfy a visual checklist.</p><textarea aria-label="Team claim draft" value={team} onChange={e=>setTeam(e.target.value)} rows="22"/><div className="button-row"><button className="primary" onClick={()=>download('INFOSCI301_team_claim.md',team)}><Download size={16}/>Download team post</button><button onClick={()=>setTab('guide')}>Return to validation</button></div></section><section className="roadmap"><h2>The additions accumulate</h2><table><thead><tr><th>Milestone</th><th>What carries forward</th><th>Evidence that changes the work</th></tr></thead><tbody><tr><td>Week 4 · individual → team</td><td>Reflection 1; field observation; basic + network + spatial–temporal design ideas</td><td>Human-only peer review, four-level questions, source and ethics boundaries</td></tr><tr><td>Week 5 · proposal + MVP</td><td>Final Group Project — Proposal; working demonstration</td><td>One question, purposeful linked views, real data, testable user task</td></tr><tr><td>Week 6 · implementation & iteration</td><td>Symposium + interactive user study</td><td>Demonstration, feedback to others and response to feedback: 15% of course grade</td></tr><tr><td>Week 7 · future-roadmap roundtable</td><td>Reflection 2; final reflection and research roadmap</td><td>Bounded future contribution, next validation and community/open-science plan: roundtable 5%</td></tr><tr><td>Final submission</td><td>Integrated, revised artifact and reproducibility record</td><td>Clearly separate demonstrated findings from future proposals</td></tr></tbody></table><p className="micro">Only two weekly reflections. The 15% + 5% split belongs to the existing 20% Symposium & Interactive Activities component; it is not additional grading weight.</p></section><blockquote>Become a designer who can reason with evidence, an innovator who connects disciplines, and a global leader who makes technology accountable to people. The future is yours to investigate—and help shape.</blockquote></section>}
  {tab==='sources'&&<section><div className="section-heading"><div><p className="eyebrow">TRACE THE EVIDENCE · BORROW THE INTERACTION PATTERN</p><h2>Sources, frontiers and design references</h2></div><button onClick={()=>download('PROVENANCE.json',JSON.stringify(data.provenance,null,2),'application/json')}><Download size={15}/>Provenance manifest</button></div><p>Examples were reviewed on 14 September 2026. They are design references, not a claim of a popularity ranking or endorsement. No reference-site code, brand assets or model outputs are copied.</p><div className="sources-grid">{SOURCES.map(([type,title,url,note])=><article key={url}><span className="eyebrow">{type}</span><h3><Link href={url}>{title}</Link></h3><p>{note}</p></article>)}</div><details><summary>Full dataset transformation and limitations</summary><pre>{JSON.stringify(data.provenance,null,2)}</pre></details></section>}
  <footer><span>{config.courseTitle} · {config.instructor}</span><span>Domain → Data/Task → Idiom → Algorithm</span><a href={BASE+'DEPLOYMENT_GUIDE.html'} target="_blank" rel="noreferrer">Setup & deployment guide<ArrowUpRight size={14}/></a></footer></main>
  {settings&&<div className="modal-backdrop" onClick={()=>setSettings(false)}><section className="modal" role="dialog" aria-modal="true" aria-label="Configure Atlas Studio" onClick={e=>e.stopPropagation()}><div className="section-heading"><h2>Configure your studio</h2><button aria-label="Close configuration" onClick={()=>setSettings(false)}><X size={18}/></button></div><p>Edit public teaching settings. No credentials, private keys or tokens belong in this file. Session changes are not automatically deployed.</p><textarea aria-label="Configuration JSON" value={configText} onChange={e=>setConfigText(e.target.value)} rows="17" spellCheck="false"/><p className="micro">githubRepo: owner/repository · notebookPath: public/notebooks in the source repository. Leave githubRepo empty until the repository exists.</p>{notice&&<p role="status">{notice}</p>}<div className="button-row"><button className="primary" onClick={applyConfig}>Apply for this session</button><button onClick={()=>{try{const c=validateConfig(JSON.parse(configText));download('config.json',JSON.stringify({...defaults,...c},null,2),'application/json');}catch(e){setNotice(e.message);}}}><Download size={16}/>Download config.json</button></div></section></div>}</>;
}
function recipe(network,lang,p){
  if(network){
    if(lang==='python')return `# Run from the source repo root; install networkx, matplotlib.\nimport json, networkx as nx\nimport matplotlib.pyplot as plt\npapers = json.load(open('public/data/emerging-tech.json'))\npapers = [p for p in papers if p['year'] >= ${p.since}][:${p.maxPapers}]\nG = nx.Graph()\nfor paper in papers:\n    G.add_node(paper['id'], kind='paper', title=paper['title'])\n    for topic in paper['topics']:\n        G.add_node(topic['id'], kind='topic', title=topic['label'])\n        G.add_edge(paper['id'], topic['id'], relation='classified under')\nassert G.number_of_edges() == sum(len(p['topics']) for p in papers)\nscores = ${p.metric==='pagerank'?'nx.pagerank(G, alpha=0.85)':'dict(G.degree())'}\n# Seeded layouts in different engines are NOT numerically identical.\npos = ${p.layout==='circular'?'nx.circular_layout(G)':p.layout==='bipartite'?"nx.bipartite_layout(G, [p['id'] for p in papers])":'nx.spring_layout(G, seed=42)'}\n${p.layout==='matrix'?"plt.imshow(nx.to_numpy_array(G), cmap='Greens'); plt.show()":"nx.draw(G, pos, node_size=[25 + 10*scores[n] for n in G]); plt.show()"}\n# Compare with a basic topic-count chart. Validate with the audience.\n# Full filter/search state is included in the evidence JSON export.`;
    if(lang==='r')return `# R adaptation; not executed in this release.\nlibrary(jsonlite); library(igraph)\npapers <- fromJSON('public/data/emerging-tech.json', simplifyVector=FALSE)\npapers <- head(Filter(function(p) p$year >= ${p.since}, papers), ${p.maxPapers})\nedges <- do.call(rbind, lapply(papers, function(p)\n  do.call(rbind, lapply(p$topics, function(t) c(p$id, t$id)))))\ng <- graph_from_edgelist(edges, directed=FALSE)\nscore <- ${p.metric==='pagerank'?'page_rank(g, damping=0.85)$vector':'degree(g)'}\nset.seed(42)\nplot(g, layout=${p.layout==='circular'?'layout_in_circle(g)':'layout_with_fr(g)'},\n     vertex.size=3+sqrt(score), vertex.label=NA)\n# Edge = provider topic assignment, not citation or verified fact.`;
    return `INPUT: first ${p.maxPapers} matching papers, year >= ${p.since}\nABSTRACTION: undirected bipartite paper–topic graph\nLAYOUT: ${p.layout}; force uses d3.randomLcg(0.42), 180 ticks\nLINK: distance 75; charge −115; collision radius 12\nMETRIC: ${p.metric}; PageRank damping .85, 80 iterations\nTRAVERSAL: breadth-first neighbors, depth ${p.depth}\n3D: force x/z; publication year y; topics on base plane\nTESTS: degree sum = 2m; PageRank sum ≈ 1; BFS frontier; no isolated phantom IDs\nFILES: src/engine.js, src/Visuals.jsx, src/Scene3D.jsx\nBOUNDARY: layout distance and centrality are not evidence of truth.`;
  }
  const dataName=p.dataset==='heritage'?'heritage.json':p.dataset==='earth'?'earth-events.json':'YOUR_LOCAL_DATA.json';
  if(lang==='python')return `# Run from source repo root; install geopandas, matplotlib.\nimport json, pandas as pd, geopandas as gpd\nimport matplotlib.pyplot as plt\ndf = pd.DataFrame(json.load(open('public/data/${dataName}')))\ndf['date'] = pd.to_datetime(df['date'], errors='raise', utc=True)\nassert df['id'].is_unique\nassert df.lon.between(-180,180).all() and df.lat.between(-90,90).all()\ndf = df[df['year'].between(${p.from}, ${p.to})]\n${p.group!=='All'?`df = df[df['group'] == ${JSON.stringify(p.group)}]\n`:''}gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.lon,df.lat), crs='EPSG:4326')\nfig, ax = plt.subplots(figsize=(10,6))\ngdf.plot(ax=ax, column='group', markersize=8, legend=True)\nplt.show()\ndf.groupby('year').size().plot.bar(title='Record count by year')\nplt.show()\n# Reproject to a suitable metric CRS before distance/area operations.\n# Designation date != construction date; EONET geometry != people affected.`;
  if(lang==='r')return `# R adaptation; not executed in this release.\nlibrary(jsonlite); library(sf); library(ggplot2)\nd <- fromJSON('public/data/${dataName}')\nd <- subset(d, year >= ${p.from} & year <= ${p.to})\n${p.group!=='All'?`d <- subset(d, group == ${JSON.stringify(p.group)})\n`:''}stopifnot(!anyDuplicated(d$id), all(abs(d$lon)<=180), all(abs(d$lat)<=90))\nplaces <- st_as_sf(d, coords=c('lon','lat'), crs=4326)\nggplot(places) + geom_sf(aes(colour=group), size=1) + theme_minimal()\n# CRS and date meaning must be verified before substantive interpretation.`;
  return `INPUT: ${dataName}; ${p.from}–${p.to}; group ${p.group}\nUNIT: ${p.dataset==='heritage'?'unique designation ID':'dated geometry / declared local record'}\nFILTER: inclusive year window; group; case-insensitive title search\nCOORDINATES: WGS84 [longitude, latitude]\nMAP: Mercator or Equal Earth; fixed extent from full dataset\nGRID: floor(projected x/18), floor(projected y/18); screen-space counts\n3D: x=normalized longitude; z=negative normalized latitude; y=normalized year\n3D bounds stay fixed to the full selected dataset across filters; NOT metric distance\nCHECK: IDs, coordinate range, date parsing, filter counts, date meaning\nBOUNDARY: visualization is not AI inference or a validated community-impact model.`;
}
