export const STUDIOS={
  network:{name:'Network intelligence',tag:'SCIENCE · CONNECTIONS · COMMUNICATION',title:'Make emerging science legible.',
    subtitle:'Trace papers and topics. Turn a knowledge map into an evidence-bounded communication strategy.',
    question:'How can a museum educator communicate emerging geospatial AI to a public audience without turning connectedness into a claim of truth?',
    boundary:'This is a paper–topic classification graph. An edge is neither a citation nor a verified scientific claim. Search rank, centrality and visual position are not research quality.',
    levels:[
      {name:'Domain situation',verb:'Listen before you map',question:'Who needs to understand this emerging technology—and what decision or misconception matters?',
        actions:['Choose an audience: community museum educator, student journalist or local decision-maker.','Write the communication decision in one sentence. List a benefit claim and a possible misunderstanding.','Inspect one original paper and ask a real audience member what evidence they would need.'],
        validate:'Domain evidence: an interview, observation or authentic task. A plausible audience persona alone does not establish a need.',
        output:'Audience + decision + misconception + evidence still needed.',prompt:'Our audience is … They need to decide/understand … Our evidence for this need is … We have not yet established …',
        transfer:'Carry your individual project question forward; let the communication audience refine it, not disappear behind the graph.'},
      {name:'Data & task abstraction',verb:'Declare what a connection means',question:'What do the nodes, edges, missing records and comparison tasks represent?',
        actions:['Inspect the 60-paper OpenAlex sample and the source link for a selected paper.','Separate paper nodes from provider-assigned topic nodes. Define the edge as “classified under.”','Compare direct degree and two-hop neighbors. Check a source record and identify one missing perspective.'],
        validate:'Abstraction evidence: verify IDs, node/edge semantics and source coverage with a domain-informed reviewer. For NLP triples, inspect the supporting text and label unverified relations as inferred.',
        output:'Data dictionary + relationship rule + task + sample boundary.',prompt:'Node = … Edge = … Task = compare/trace/find … This sample excludes … Inferred relationships are labeled …',
        transfer:'Add a reproducible relationship table to your group project; do not invent edges just to fill a network.'},
      {name:'Idiom & interaction',verb:'Choose a view for a task',question:'Does a node-link view help your audience trace a relationship better than a matrix or a simple chart?',
        actions:['Compare force, circular, bipartite and adjacency-matrix views with the same filters.','Select a topic; use the one/two-hop control. Compare the basic topic-count chart with the richer graph.','Ask a peer to find a paper connecting two themes. Record errors, time, confidence and their interpretation of the legend.'],
        validate:'Idiom evidence: an observed task comparison with a simpler baseline. A visually attractive screenshot is not a usability result.',
        output:'Encoding/interaction rationale + baseline comparison + observed task result.',prompt:'The user task is … Our basic baseline is … The network adds … In the peer test we observed … We will change …',
        transfer:'Your basic idiom answers “how much”; your network must add a relationship or pathway that the baseline cannot show clearly.'},
      {name:'Algorithm',verb:'Make the computation inspectable',question:'Are layout, traversal and centrality implemented correctly and fast enough for the defined task?',
        actions:['Change visible papers, then compare degree with PageRank. PageRank here runs on undirected paper–topic links.','Inspect the code recipe: deterministic force layout seed 0.42; 180 ticks; BFS depth; PageRank damping 0.85.','Run the Colab. Check IDs, counts, rank normalization and sensitivity to sample size before communicating any result.'],
        validate:'Algorithm evidence: unit tests, invariant checks, reproducible parameters and performance measurements. Correct computation cannot validate the upstream audience need.',
        output:'Algorithm + parameters + tests + limitations + reproducibility link.',prompt:'We computed … with parameters … Our correctness check was … The result changed when … This does not establish …',
        transfer:'Attach code and a claim-to-evidence record to the Week 5 MVP; use Week 6 feedback to decide Keep, Revise or Investigate.'}
    ]},
  spatial:{name:'Place & time intelligence',tag:'PEOPLE · HERITAGE · EARTH',title:'Read change. Keep people in view.',
    subtitle:'Explore real heritage designations through place and time—and distinguish mapped evidence from community meaning.',
    question:'How could a community heritage team compare what an official archive recognizes, when recognition occurred, and whose stories remain absent?',
    boundary:'A landmark designation date is not its construction date, visitor experience or cultural worth. These NYC records teach a method; they do not document Jinxi or establish local consent.',
    levels:[
      {name:'Domain situation',verb:'Start with a situated human question',question:'Who defines heritage value, who is affected by the map, and what would a useful decision look like?',
        actions:['Choose a heritage interpretation task: planning an accessible story walk, questioning archive coverage, or explaining designation history.','Separate the administrative data from lived experience. Write one question for a resident or museum practitioner.','For Jinxi fieldwork, record observation vs interpretation, permissions and a non-identifying evidence plan.'],
        validate:'Domain evidence: community-defined needs, an observation/interview protocol and permission boundaries. Satellite imagery or official records alone cannot reveal lived experience.',
        output:'Stakeholder question + situated context + consent/benefit boundary.',prompt:'The community/user question is … Official data can show … We must ask people about … We will not collect/publish …',
        transfer:'Revisit your individual project and field observation: which assumption would community knowledge change?'},
      {name:'Data & task abstraction',verb:'Separate event, place and time',question:'What exactly is dated, located, counted and missing?',
        actions:['Inspect one landmark record: designation ID, representative coordinate, designation date and borough.','Use year and borough filters; distinguish a unique designation from its constituent building records.','Switch to NASA EONET: the unit changes to dated event geometry. Explain why point count is not event count or people affected.'],
        validate:'Abstraction evidence: units, coordinate reference, date meaning, deduplication, missingness and coverage checks. A gap in the dataset is not proof of absence.',
        output:'Spatial–temporal data dictionary + unit + CRS + provenance + coverage limitation.',prompt:'One row means … Time means … Coordinates use WGS84 longitude/latitude … Missingness matters because …',
        transfer:'Choose a legitimate spatial–temporal question for your group project; if no relevant data exist, state the gap and design an ethical collection plan.'},
      {name:'Idiom & interaction',verb:'Compare a map, a timeline and a cube',question:'Which representation helps a person explain change without mistaking density for importance?',
        actions:['Compare individual points and a projected screen-grid aggregation with the same year window.','Use the linked timeline and record table. In 3D, height encodes year—not importance or building height.','Ask a peer to identify an early vs late designation, then explain one apparent gap. Test the 2D view against the 3D space–time cube.'],
        validate:'Idiom evidence: task success, misreadings, accessibility and a 2D baseline. 3D is retained only if it helps the actual task.',
        output:'Linked-view design + time semantics + legend + observed comparison.',prompt:'Our basic timeline shows … The map adds … The 3D view helps/hurts because … A user misread … We revised …',
        transfer:'Your project combines a basic summary, a meaningful network and a place/time view. Every addition must change a decision or interpretation.'},
      {name:'Algorithm',verb:'Validate the spatial computation',question:'Do filtering, projection, aggregation and time encoding preserve the intended meaning?',
        actions:['Check longitude/latitude order, valid ranges, date parsing and unique IDs. Compare counts before and after filtering.','Compare Mercator and Equal Earth on the global NASA view. A screen grid is visual aggregation, not equal-area density estimation.','Run the Python notebook; record CRS before distance/area operations. Treat AI/remote-sensing predictions as estimates requiring held-out and human review.'],
        validate:'Algorithm evidence: coordinate/date tests, count reconciliation, projection checks and sensitivity analyses. No AI inference is performed by this browser map.',
        output:'Reproducible transformation + validation checks + uncertainty/impact boundary.',prompt:'Our spatial operation is … We verified … The aggregation changes when … Human review is needed for …',
        transfer:'Week 5: working map/time MVP. Week 6: observed user study and logged revisions. Week 7: bounded human-centered AI/digital-humanities research roadmap.'}
    ]}
};
export const PACKAGES=[
  ['NetworkX','Force, circular, spectral, Kamada–Kawai; centrality, BFS, communities','Python notebook: executed core examples','https://networkx.org/documentation/stable/','network_layout_comparison.png','network'],
  ['PyVis / vis-network','Interactive node-link exploration','Saved notebook output; external scripts may need internet','https://pyvis.readthedocs.io/','karate_pyvis.html','network'],
  ['Plotly','Selectable network and time/map animation','Executed notebook examples','https://plotly.com/python/','karate_plotly.html','network'],
  ['pyCirclize','Circular relationship encodings','Executed notebook example','https://moshi4.github.io/pyCirclize/','network_pycirclize.png','network'],
  ['Graphviz','Directed reasoning / dependency layout','DOT source provided; executable was unavailable in the prior notebook run','https://graphviz.org/documentation/','network_reasoning_graphviz.gv','network'],
  ['D3 + Three.js','Live force / bipartite / matrix; selectable 3D nodes','Runs in this app; separate from Python package execution','https://d3js.org/','', 'network'],
  ['spaCy + RDFLib','NLP entity/relation extraction → provenance-bearing knowledge graph','Advanced extension; inferred triples require source-text review','https://spacy.io/usage/linguistic-features','', 'network'],
  ['GeoPandas + Shapely','CRS-aware vector data and spatial transformations','Executed notebook map','https://geopandas.org/','eonet_geopandas_map.png','spatial'],
  ['Cartopy','Projection-aware Earth observation maps','Executed notebook projection comparison','https://scitools.org.uk/cartopy/docs/latest/','eonet_cartopy_robinson.png','spatial'],
  ['Folium / Leaflet','Interactive map with record popups','Saved notebook output; basemap tiles need internet','https://python-visualization.github.io/folium/latest/','eonet_folium.html','spatial'],
  ['pydeck / deck.gl','GPU point and layer rendering','Executed notebook export; WebGL/browser support varies','https://deckgl.readthedocs.io/','eonet_pydeck.html','spatial'],
  ['Datashader','Pixel aggregation for dense observations','Executed count-grid example; not population risk','https://datashader.org/','eonet_datashader_density.png','spatial'],
  ['Rasterio + xarray','Raster grid output / labeled spatial–temporal arrays','Rasterio output included; xarray is an extension path','https://rasterio.readthedocs.io/','eonet_event_count_grid.tif','spatial'],
  ['OSMnx','Street-network analysis and urban mobility','Notebook builds an OSMnx-compatible event graph; not a downloaded street network','https://osmnx.readthedocs.io/','eonet_osmnx_compatible_graph.png','spatial'],
  ['geemap / Earth Engine','Satellite time series, overlays, inspection','Optional account/project setup; not run by this static app','https://geemap.org/','', 'spatial'],
  ['CesiumJS / OpenDroneMap','Digital Earth, 3D tiles, drone-derived reconstruction','Advanced extension; not an executed reconstruction here','https://cesium.com/learn/cesiumjs-learn/','', 'spatial']
];
export const SOURCES=[
  ['Four-level framework','Munzner: A Nested Model for Visualization Design and Validation (2009)','https://www.cs.ubc.ca/labs/imager/tr/2009/NestedModel/','A different evidence test belongs to each level; later correctness does not rescue an invalid domain abstraction.'],
  ['Real data','OpenAlex metadata and API','https://docs.openalex.org/','60 search results about geospatial artificial intelligence. Metadata and topic labels, not a systematic literature review.'],
  ['Real data','NYC Landmarks Preservation Commission dataset','https://data.cityofnewyork.us/Housing-Development/Designated-and-Calendared-Buildings-and-Sites/ncre-qhxs','1,457 unique designation IDs after the documented coordinate/date checks and deduplication.'],
  ['Real data','NASA EONET v3','https://eonet.gsfc.nasa.gov/docs/v3','272 dated geometries from the bundled category snapshots, not an exhaustive hazard census.'],
  ['Research','Foundation Models for Generalist Geospatial Artificial Intelligence','https://arxiv.org/abs/2310.18660','Prithvi motivates reusable EO representations; downstream validity still requires task-specific evidence.'],
  ['Open source','NASA–IMPACT: Prithvi EO 2.0','https://github.com/NASA-IMPACT/Prithvi-EO-2.0','Optional model frontier. This app does not download weights, train or run inference.'],
  ['Research','Reconfiguring Geovisualization in the Age of Generative AI (2026 preprint)','https://arxiv.org/abs/2608.12059','Expert-interview study foregrounding judgment, spatial validation, provenance and accountability; a preprint, not universal evidence.'],
  ['Research','Assessing Foundation Models in Permafrost Mapping','https://arxiv.org/abs/2401.08787','A concrete reminder to examine domain generalization before treating a vision model as universally reliable.'],
  ['Frontier','Google Earth Engine documentation','https://developers.google.com/earth-engine','Satellite imagery and geospatial computation; access/project configuration is separate from this local demo.'],
  ['Frontier','IEEE GRSS Data Fusion Contest','https://www.grss-ieee.org/community/technical-committees/2026-ieee-grss-data-fusion-contest/','Benchmark discussion path; consult the source for task, data access and evaluation conditions.'],
  ['Frontier','OpenDroneMap documentation','https://docs.opendronemap.org/','Drone reconstruction pipeline; permission, provenance and ground validation come before public sharing.'],
  ['HF UI reference','TencentARC / InstantMesh','https://huggingface.co/spaces/TencentARC/InstantMesh','Adopt: input → processed views → 3D result, example presets, explicit settings and separate downloads.'],
  ['HF UI reference','TRELLIS community Space','https://huggingface.co/spaces/trellis-community/TRELLIS','Adopt: progressive settings and clear output states. Microsoft Space currently redirects to this community instance.'],
  ['HF UI reference','DeepSite','https://deepsite.hf.co/','Adopt: a clear starting action. Only the public landing flow was inspected; no claim of testing its editor.'],
  ['Vercel UI reference','React Three Next starter','https://react-three-next.vercel.app/','Adopt: coordinated DOM + 3D interactions and shared-canvas thinking, not its branding.'],
  ['Vercel UI reference','Threejs-Punk','https://threejspunk.vercel.app/','Atmosphere reference only. Avoid heavy visual effects that obscure data or harm classroom performance.'],
  ['Vercel UI reference','Vercel: interactive 3D event badge','https://vercel.com/blog/building-an-interactive-3d-event-badge-with-react-three-fiber','Adopt: direct manipulation and tactile feedback. This teaching app uses Three.js directly, not the badge source.']
];
export const TEAM_TEMPLATE=`TEAM CLAIM — INFOSCI 301\n\n1. Title and shared research question:\nTeam members, individual strengths and specific responsibilities:\nWhich individual-project evidence each member brings:\n\n2. Contribution and boundaries:\nSDG target + plausible contribution + evidence needed (no unsupported impact claim):\nLocal community/user + observed need + engagement/consent plan:\nOpen science: data/code provenance, reproducibility, licenses and sharing restrictions:\n\n3. One cumulative visualization design:\nBasic idiom + task + data source:\nNetwork: nodes, edges, relationship rule, audience/task + data source:\nSpatial–temporal: place, time meaning, unit, user/task + data source:\nWhy each addition changes an interpretation or decision:\n\n4. Four-level validation and next milestone:\nDomain evidence / abstraction checks / idiom user test / algorithm checks:\nWeek 5 proposal + working MVP scope:\nWeek 6 user-study task + feedback/response plan:\nWeek 7 future-roadmap question:\nKnown gaps and what we will NOT claim:\n`;
